In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#import the data
dataset = pd.read_csv("Salary_Data.csv")

x1 = dataset.iloc[:, :-1].values
y1 = dataset.iloc[:,1].values

#spliting dataset into Training set and Test set 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x1,y1, test_size=0.2, random_state=0) 

In [11]:
x_train

array([[ 1.75832984],
       [-0.40973925],
       [ 0.09356251],
       [ 1.10016601],
       [-0.83560996],
       [ 0.01613147],
       [-0.7194634 ],
       [-0.21616165],
       [ 1.21631257],
       [ 0.6742953 ],
       [-1.45505827],
       [ 2.10676952],
       [-0.79689444],
       [-1.1066186 ],
       [ 0.32585562],
       [ 0.36457114],
       [-0.52588581],
       [-0.7194634 ],
       [ 1.52603672],
       [-1.18404964],
       [-1.53248931],
       [ 0.79044186],
       [-0.06129957],
       [-0.40973925]])

In [12]:
x_test

array([[-1.46136985],
       [ 1.19933112],
       [-0.67525365],
       [-0.73572413],
       [ 0.95744921],
       [ 0.7155673 ]])

In [13]:
y_train

array([[ 1.56283548],
       [-0.72970392],
       [ 0.37113122],
       [ 1.1057473 ],
       [-0.69550196],
       [-0.31690082],
       [-0.3807875 ],
       [-0.51525604],
       [ 1.61030683],
       [ 0.72000731],
       [-1.11645222],
       [ 1.93538674],
       [-0.55401557],
       [-1.3711116 ],
       [ 0.30155767],
       [ 0.80881947],
       [-0.67344009],
       [-0.78411245],
       [ 1.27837039],
       [-1.22454331],
       [-1.39321381],
       [ 0.98358017],
       [-0.23990609],
       [-0.68279723]])

In [14]:
y_test

array([[-1.41964718],
       [ 1.15180068],
       [-0.8319137 ],
       [-0.64550955],
       [ 0.98711381],
       [ 0.75815593]])

In [16]:
x_train.reshape(-1,1)

array([[ 1.75832984],
       [-0.40973925],
       [ 0.09356251],
       [ 1.10016601],
       [-0.83560996],
       [ 0.01613147],
       [-0.7194634 ],
       [-0.21616165],
       [ 1.21631257],
       [ 0.6742953 ],
       [-1.45505827],
       [ 2.10676952],
       [-0.79689444],
       [-1.1066186 ],
       [ 0.32585562],
       [ 0.36457114],
       [-0.52588581],
       [-0.7194634 ],
       [ 1.52603672],
       [-1.18404964],
       [-1.53248931],
       [ 0.79044186],
       [-0.06129957],
       [-0.40973925]])

In [18]:
#feature scalling 
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train.reshape(-1,1))
x_test = sc_x.fit_transform(x_test.reshape(-1,1))
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train.reshape(-1,1))
y_test = sc_y.fit_transform(y_test.reshape(-1,1))

In [19]:
x_train

array([[ 1.75832984],
       [-0.40973925],
       [ 0.09356251],
       [ 1.10016601],
       [-0.83560996],
       [ 0.01613147],
       [-0.7194634 ],
       [-0.21616165],
       [ 1.21631257],
       [ 0.6742953 ],
       [-1.45505827],
       [ 2.10676952],
       [-0.79689444],
       [-1.1066186 ],
       [ 0.32585562],
       [ 0.36457114],
       [-0.52588581],
       [-0.7194634 ],
       [ 1.52603672],
       [-1.18404964],
       [-1.53248931],
       [ 0.79044186],
       [-0.06129957],
       [-0.40973925]])